In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [3]:
df = pd.read_csv('mtcars_for_manymerge.csv')
df.head()

Cars   mpg  cyl   disp   hp  drat  Feedback
0           MazdaRX4  21.0    6  160.0  110  3.90         1
1       MazdaRX4_WAG  21.0    6  160.0  110  3.90         0
2         Datsun_710  22.8    4  108.0   93  3.85         1
3     Hornet_4_Drive  21.4    6  258.0  110  3.08         1
4  Hornet_Sportabout  18.7    8  360.0  175  3.15         1

In [4]:
df.shape

(21, 7)

In [5]:
X = df[['cyl', 'hp']]
y = df['Feedback']

#### K-Nearest Neighbour

In [6]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)
y_pred = knn.predict(X)
accuracy_score(y, y_pred)

0.6666666666666666

In [7]:
cross_val_score(knn, X, y, cv = 5)

array([0.4 , 1.  , 0.75, 1.  , 0.25])

In [8]:
cross_val_score(knn, X, y, cv = 5).mean()

0.6799999999999999

#### Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, y)
y_pred = model.predict(X)
accuracy_score(y, y_pred)

0.5714285714285714

In [10]:
cross_val_score(model, X, y, cv = 5)

array([0.2 , 0.5 , 0.25, 0.5 , 0.5 ])

In [11]:
cross_val_score(model, X, y, cv = 5).mean()

0.39

#### Decision Tree

In [12]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(X, y)
y_pred = clf.predict(X)
accuracy_score(y, y_pred)

0.9047619047619048

In [13]:
cross_val_score(clf, X, y, cv = 5)

array([0.6 , 1.  , 0.75, 0.25, 0.25])

In [14]:
cross_val_score(clf, X, y, cv = 5).mean()

0.5700000000000001

#### Random Forest classifier

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()
rf_clf.fit(X, y)
y_pred = rf_clf.predict(X)
accuracy_score(y, y_pred)

0.9047619047619048

In [17]:
cross_val_score(rf_clf, X, y, cv = 5)

array([0.6 , 1.  , 0.75, 0.75, 0.25])

In [18]:
cross_val_score(rf_clf, X, y, cv = 5).mean()

0.67