In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [3]:
data = pd.read_csv('iris.csv')
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
data.shape

(150, 5)

In [4]:
X = data.drop('Species', axis = 1)
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [5]:
X.shape

(150, 4)

In [ ]:
# Step 1: Apply PCA on the indepedent features (varaiables) X

In [6]:
pca = PCA()
principalComponents = pca.fit_transform(X)
print(principalComponents)

[[-2.68420713e+00  3.26607315e-01 -2.15118370e-02  1.00615724e-03]
 [-2.71539062e+00 -1.69556848e-01 -2.03521425e-01  9.96024240e-02]
 [-2.88981954e+00 -1.37345610e-01  2.47092410e-02  1.93045428e-02]
 [-2.74643720e+00 -3.11124316e-01  3.76719753e-02 -7.59552741e-02]
 [-2.72859298e+00  3.33924564e-01  9.62296998e-02 -6.31287327e-02]
 [-2.27989736e+00  7.47782713e-01  1.74325619e-01 -2.71468037e-02]
 [-2.82089068e+00 -8.21045110e-02  2.64251085e-01 -5.00996251e-02]
 [-2.62648199e+00  1.70405349e-01 -1.58015103e-02 -4.62817610e-02]
 [-2.88795857e+00 -5.70798026e-01  2.73354061e-02 -2.66154143e-02]
 [-2.67384469e+00 -1.06691704e-01 -1.91533300e-01 -5.58909660e-02]
 [-2.50652679e+00  6.51935014e-01 -6.92749958e-02 -1.66082478e-02]
 [-2.61314272e+00  2.15206320e-02  1.07650353e-01 -1.57704569e-01]
 [-2.78743398e+00 -2.27740189e-01 -2.00327788e-01 -7.23508674e-03]
 [-3.22520045e+00 -5.03279909e-01  6.84136292e-02 -2.19466641e-02]
 [-2.64354322e+00  1.18619490e+00 -1.44505704e-01  1.56980962e

In [7]:
principalComponents.shape

(150, 4)

In [9]:
np.round(principalComponents,2)

array([[-2.68,  0.33, -0.02,  0.  ],
       [-2.72, -0.17, -0.2 ,  0.1 ],
       [-2.89, -0.14,  0.02,  0.02],
       [-2.75, -0.31,  0.04, -0.08],
       [-2.73,  0.33,  0.1 , -0.06],
       [-2.28,  0.75,  0.17, -0.03],
       [-2.82, -0.08,  0.26, -0.05],
       [-2.63,  0.17, -0.02, -0.05],
       [-2.89, -0.57,  0.03, -0.03],
       [-2.67, -0.11, -0.19, -0.06],
       [-2.51,  0.65, -0.07, -0.02],
       [-2.61,  0.02,  0.11, -0.16],
       [-2.79, -0.23, -0.2 , -0.01],
       [-3.23, -0.5 ,  0.07, -0.02],
       [-2.64,  1.19, -0.14,  0.16],
       [-2.38,  1.34,  0.28,  0.  ],
       [-2.62,  0.82,  0.15,  0.16],
       [-2.65,  0.32,  0.03,  0.08],
       [-2.2 ,  0.88, -0.11,  0.03],
       [-2.59,  0.52,  0.22, -0.07],
       [-2.31,  0.4 , -0.23, -0.02],
       [-2.54,  0.44,  0.21,  0.04],
       [-3.22,  0.14,  0.3 ,  0.  ],
       [-2.3 ,  0.11,  0.05,  0.15],
       [-2.36, -0.03,  0.13, -0.3 ],
       [-2.51, -0.14, -0.25,  0.04],
       [-2.47,  0.14,  0.1 ,  0.06],
 

In [ ]:
# Step 2 : Check for the variance ratio of the individual principal components

In [14]:
np.round(pca.explained_variance_ratio_,2)

array([0.92, 0.05, 0.02, 0.01])

In [12]:
PC1_vr = 0.92461621
PC2_vr = 0.05301557
np.round(PC1_vr + PC2_vr,2)

0.98

In [13]:
PC3_vr = 0.01718514 
PC4_vr = 0.00518309
np.round(PC3_vr + PC4_vr,2)

0.02

In [ ]:
# Step 3 : Decide the number of components that the project needs and recreate the PCA model
# and the principal components

In [15]:
# Create a PCA model for 2 components
pca = PCA(n_components = 2)
principalComponents = pca.fit_transform(X)
print(principalComponents)

[[-2.68420713  0.32660731]
 [-2.71539062 -0.16955685]
 [-2.88981954 -0.13734561]
 [-2.7464372  -0.31112432]
 [-2.72859298  0.33392456]
 [-2.27989736  0.74778271]
 [-2.82089068 -0.08210451]
 [-2.62648199  0.17040535]
 [-2.88795857 -0.57079803]
 [-2.67384469 -0.1066917 ]
 [-2.50652679  0.65193501]
 [-2.61314272  0.02152063]
 [-2.78743398 -0.22774019]
 [-3.22520045 -0.50327991]
 [-2.64354322  1.1861949 ]
 [-2.38386932  1.34475434]
 [-2.6225262   0.81808967]
 [-2.64832273  0.31913667]
 [-2.19907796  0.87924409]
 [-2.58734619  0.52047364]
 [-2.3105317   0.39786782]
 [-2.54323491  0.44003175]
 [-3.21585769  0.14161557]
 [-2.30312854  0.10552268]
 [-2.35617109 -0.03120959]
 [-2.50791723 -0.13905634]
 [-2.469056    0.13788731]
 [-2.56239095  0.37468456]
 [-2.63982127  0.31929007]
 [-2.63284791 -0.19007583]
 [-2.58846205 -0.19739308]
 [-2.41007734  0.41808001]
 [-2.64763667  0.81998263]
 [-2.59715948  1.10002193]
 [-2.67384469 -0.1066917 ]
 [-2.86699985  0.0771931 ]
 [-2.62522846  0.60680001]
 

In [ ]:
# By losing 2 coulmns we are still able to retain 98% information of the dataset

In [ ]:
# Step 4 : Create a new dataframe with these Principal components and the labels (y)

In [16]:
df_iris_transformed = pd.DataFrame(principalComponents, columns=['PC1', 'PC2'])
df_iris_transformed

PC1       PC2
0   -2.684207  0.326607
1   -2.715391 -0.169557
2   -2.889820 -0.137346
3   -2.746437 -0.311124
4   -2.728593  0.333925
..        ...       ...
145  1.944017  0.187415
146  1.525664 -0.375021
147  1.764046  0.078519
148  1.901629  0.115877
149  1.389666 -0.282887

[150 rows x 2 columns]

In [17]:
df_iris_transformed['Species'] = data['Species']
df_iris_transformed.head()

PC1       PC2      Species
0 -2.684207  0.326607  Iris-setosa
1 -2.715391 -0.169557  Iris-setosa
2 -2.889820 -0.137346  Iris-setosa
3 -2.746437 -0.311124  Iris-setosa
4 -2.728593  0.333925  Iris-setosa

In [20]:
df_iris_transformed.shape

(150, 3)

In [21]:
df_iris_transformed['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
# Step 5: Create a Logistic Regression model on this dataset

In [22]:
X = df_iris_transformed.drop('Species', axis = 1)
y = df_iris_transformed.Species

In [23]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [ ]:
# A user has collected the following values of the Iris flower and wants the model to predict its class
# SL = 5.1, SW = 3.5, PL = 1.4, PW = 0.2

In [ ]:
## ValueError: X has 4 features, but LogisticRegression is expecting 2 features as input.

In [27]:
sepalLength = float(input('Sepal Length: '))
sepalWidth = float(input('Sepal Width: '))
petalLength = float(input('Petal Length: '))
petalWidth = float(input('Petal Width: '))
featureSet = np.array([[sepalLength, sepalWidth, petalLength, petalWidth]])
transformed_ds = pca.transform(featureSet)
model.predict(transformed_ds)

Sepal Length:  5.1
Sepal Width:  3.5
Petal Length:  1.4
Petal Width:  0.2


array(['Iris-setosa'], dtype=object)

In [28]:
transformed_ds

array([[-2.68420713,  0.32660731]])